version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    rust: "1.74"

# Maybe mkdocs is better for this???

# TODO: THIS SHOULD STILL BE CONFIGURED
python:
  install:
    # TODO: CHANGE THIS
    - requirements: docs/requirements.txt
    - method: pip
      path: . # TODO: ????

# TODO: THIS SHOULD STILL BE CONFIGURED
sphinx:
  configuration: docs/source/conf.py