# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# FIXME: CONFIGURE THIS

# TODO: Make it read from here https://docs.readthedocs.io/en/stable/guides/setup/monorepo.

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
    rust: "1.74"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements-doc.txt

#   # TODO: THIS SHOULD STILL BE CONFIGURED
# python:
#   install:
#     # TODO: CHANGE THIS
#     - requirements: docs/requirements.txt
#     - method: pip
#       path: . # TODO: ????

# # TODO: THIS SHOULD STILL BE CONFIGURED
# sphinx:
#   configuration: docs/source/conf.py