[package]
name = "rdf-builder-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# crate-type = ["cdylib"]

[dependencies]
log = { version = "0.4", optional = true }
thiserror = "1.0.38"

[features]
default = []
logging = ["dep:log"]
